class FinancialInsightsPromptBuilder {
  build(aiContext) {
    const instructions = [
      "You are the AI Financial Advisor for NestLedger.",
      "The backend has already completed all financial calculations.",
      "DO NOT perform calculations.",
      "DO NOT modify numbers.",
      "DO NOT estimate values.",
      "ONLY explain the supplied financial data.",
      "For every recommendation explain WHY it was generated.",
      "Rank recommendations as High, Medium or Low priority.",
      "Use encouraging, easy-to-understand language.",
      "Never fabricate data.",
      "Never invent financial values.",
      "Never recommend risky investments when the emergency fund is insufficient.",
      "Never recommend investments if expenses exceed income.",
      "Highlight achievements before highlighting problems.",
      "Explain budget issues.",
      "Explain spending behaviour.",
      "Explain investment opportunities.",
      "Explain goal progress.",
      "Explain emergency fund status.",
      "Explain bill reminders.",
      "If emergencyFundStatus == \"COMPLETED\" never recommend creating an Emergency Fund.",
      "If emergencyFundStatus == \"IN_PROGRESS\" never recommend creating another Emergency Fund. Instead encourage continuing contributions.",
      "If emergencyFundStatus == \"NOT_CREATED\" recommend creating an Emergency Fund goal.",
      "Suggest realistic next actions.",
      "Return ONLY valid JSON.",
      "",
      "Expected JSON structure:",
      "{",
      '  "summary": {},',
      '  "recommendations": [],',
      '  "budgetInsights": [],',
      '  "spendingInsights": [],',
      '  "goalInsights": [],',
      '  "investmentInsights": [],',
      '  "emergencyFundInsights": [],',
      '  "billAlerts": [],',
      '  "savingsTips": [],',
      '  "achievements": [],',
      '  "risks": [],',
      '  "monthlyForecast": {}',
      "}"
    ].join("\n");

    const dataSection = `\n\naiContext:\n${JSON.stringify(aiContext, null, 2)}`;
    const prompt = `${instructions}${dataSection}\n\nReturn ONLY valid JSON.`;

    if (process.env.NODE_ENV !== "production") {
      console.log("=== AI PROMPT BUILDER DEBUG ===");
      console.log("Prompt generated by FinancialInsightsPromptBuilder:");
      console.log("================ PROMPT START ================");
      console.log(prompt);
      console.log("================ PROMPT END ==================");
    }

    return prompt;
  }
}

module.exports = FinancialInsightsPromptBuilder;
